package it.polimi.ingsw.model.game;

import java.util.Random;

/**
 * The {@code Dice} class represents a die (singular of dice) that can be rolled to generate random numbers.
 * It manages a `number` representing the current value of the die and uses a {@link Random} instance
 * for generating random numbers between 1 and 6.
 *
 * <p>
 * This class is typically used in games that require dice rolls for random number generation.
 * </p>
 */
public class Dice {
    private int number;
    private Random random;

    /**
     * Constructor for the {@code Dice} class.
     * Initializes the die with a default value of 6 and sets up the Random instance for generating
     * random values.
     */
    public Dice() {
        this.number = 6;
        this.random = new Random();
    }

    /**
     * Gets the current value of the die.
     *
     * @return the current number on the die.
     */
    public int getNumber() {
        return number;
    }

    /**
     * Rolls the die to generate a random number between 1 and 6 (inclusive).
     * Updates the current value of the die and returns it.
     *
     * @return the new number generated by rolling the die.
     */
    public int thr() {
        number = random.nextInt(6) + 1;
        return number;
    }
}